# Generated by Django 5.2.8 on 2025-12-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_product_available_rooms_product_total_rooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('room', 'Room'), ('food', 'Food')], default='room', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_rooms',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu_app.hotel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
